version: "3.1"

services:

  database:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "Password4."
    ports:
      - "5432:5432"
    networks:
      - sbnet

  devops-gradle:
    image: merveagacayak/app:latest
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: "Password4."
      SPRING_JPA_DATABASE: postgresql
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_OPEN_IN_VIEW: false
    networks:
      - sbnet

volumes:
  postgres_data:
    external: true

networks:
  sbnet:
    external: true
